create table if not exists public.dishes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null default '其他',
  created_at timestamptz not null default now()
);

create table if not exists public.meal_picks (
  id bigint generated by default as identity primary key,
  dish_id bigint not null references public.dishes(id) on delete cascade,
  selected_at timestamptz not null default now()
);

create index if not exists meal_picks_selected_at_idx on public.meal_picks (selected_at desc);

alter table public.dishes enable row level security;
alter table public.meal_picks enable row level security;

drop policy if exists "public read dishes" on public.dishes;
drop policy if exists "public write dishes" on public.dishes;
drop policy if exists "public delete dishes" on public.dishes;
drop policy if exists "public read picks" on public.meal_picks;
drop policy if exists "public write picks" on public.meal_picks;
drop policy if exists "public delete picks" on public.meal_picks;

create policy "public read dishes"
  on public.dishes
  for select
  using (true);

create policy "public write dishes"
  on public.dishes
  for insert
  with check (true);

create policy "public delete dishes"
  on public.dishes
  for delete
  using (true);

create policy "public read picks"
  on public.meal_picks
  for select
  using (true);

create policy "public write picks"
  on public.meal_picks
  for insert
  with check (true);

create policy "public delete picks"
  on public.meal_picks
  for delete
  using (true);
